"""
Pantheon sandbox API models — the single source of truth for inter-service communication.

All teams import from this module. Do not duplicate these models elsewhere.
Coordinate with Pablo before making any changes.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field

# --- Type aliases -----------------------------------------------------------

type AnalysisType = Literal["static", "dynamic", "both"]
type RiskLevel = Literal["low", "medium", "high", "critical"]
type JobStatus = Literal["queued", "running", "complete", "failed"]


# --- IOC sub-models ---------------------------------------------------------

class NetworkIOCs(BaseModel):
    """Network-layer indicators of compromise."""

    ips: list[str] = Field(default_factory=list, description="Malicious IP addresses")
    domains: list[str] = Field(default_factory=list, description="Malicious domains")
    ports: list[int] = Field(default_factory=list, description="Destination ports")
    protocols: list[str] = Field(default_factory=list, description="Network protocols used")
    urls: list[str] = Field(default_factory=list, description="Full URLs contacted")


class FileIOCs(BaseModel):
    """File-system indicators of compromise."""

    sha256: str = Field(default="", description="SHA-256 hash of the sample")
    md5: str = Field(default="", description="MD5 hash of the sample")
    paths: list[str] = Field(
        default_factory=list,
        description="File paths created or modified by the malware",
    )


# --- Request / Response models ----------------------------------------------

class AnalyzeRequest(BaseModel):
    """Request body for POST /sandbox/analyze."""

    job_id: str = Field(description="Unique job identifier, generated by the caller")
    file_content_b64: str = Field(description="Base64-encoded bytes of the malware sample")
    filename: str = Field(description="Original filename of the sample")
    analysis_type: AnalysisType = Field(
        default="both",
        description="Which analysis pipeline(s) to run",
    )


class AnalyzeResponse(BaseModel):
    """Response body for POST /sandbox/analyze."""

    job_id: str
    status: JobStatus


class ThreatReport(BaseModel):
    """Full analysis report returned by GET /sandbox/report/{job_id}."""

    job_id: str
    status: JobStatus
    malware_type: str = Field(description="e.g. 'WSH dropper', 'ransomware loader'")
    obfuscation_technique: str = Field(
        description="e.g. 'javascript-obfuscator _0x string array'"
    )
    behavior: list[str] = Field(
        default_factory=list,
        description="Observed or inferred behavioral indicators",
    )
    network_iocs: NetworkIOCs = Field(default_factory=NetworkIOCs)
    file_iocs: FileIOCs = Field(default_factory=FileIOCs)
    registry_iocs: list[str] = Field(
        default_factory=list,
        description="Registry keys created, modified, or queried",
    )
    risk_level: RiskLevel
    affected_systems: list[str] = Field(
        default_factory=list,
        description="Systems or data stores potentially impacted",
    )
    gemini_summary: str = Field(
        description="Plain-language behavioral analysis from Gemini"
    )
    remediation_hints: list[str] = Field(
        default_factory=list,
        description="High-level remediation suggestions from static/dynamic analysis",
    )


class IOCReport(BaseModel):
    """Flat IOC list returned by GET /sandbox/iocs/{job_id}."""

    ips: list[str] = Field(default_factory=list)
    domains: list[str] = Field(default_factory=list)
    file_hashes: dict[str, str] = Field(
        default_factory=dict,
        description="Hash type -> hex digest, e.g. {'sha256': '...', 'md5': '...'}",
    )
    file_paths: list[str] = Field(default_factory=list)
    ports: list[int] = Field(default_factory=list)
    registry_keys: list[str] = Field(default_factory=list)
    cve_ids: list[str] = Field(default_factory=list)
    urls: list[str] = Field(default_factory=list)


class HealthResponse(BaseModel):
    """Response body for GET /sandbox/health."""

    status: Literal["ok", "degraded"]
    docker_available: bool
    version: str = "0.1.0"
